### ISSUE TITLE
Issues with window sizing in Windows & Linux

### ISSUE THREAD

**Issue by alexkim205** [alexkim205/G-Desktop-Suite#22]
There's an offset in Windows at the top (in blue) because Windows puts its menu bar in the frame. BrowserView is absolutely positioned in the frame, which is why the  bottom is cut off. I still don't know why the right is cut off.

* Investigate shenanigans with `electron-window-state` in windows.

![Annotation 2020-05-15 200021](https://user-images.githubusercontent.com/13460330/82105067-6be4f400-96e7-11ea-9e76-d87b504609c7.png)

**Comment by compliment** [comment]
Same behavior on Linux too, although it's just the Drive page
![Screenshot from 2020-05-16 13-04-59](https://user-images.githubusercontent.com/22877365/82113740-fd02ac00-9775-11ea-8a47-64a76f1795bb.png)

**Comment by ndom91** [comment]
Same behavior on Windows on Gmail:

![image](https://user-images.githubusercontent.com/7415984/82128276-3e1caf80-97ba-11ea-9bcd-2fc58523f987.png)

**Comment by ndom91** [comment]
> Same behavior on Linux too, although it's just the Drive page
> ![Screenshot from 2020-05-16 13-04-59](https://user-images.githubusercontent.com/22877365/82113740-fd02ac00-9775-11ea-8a47-64a76f1795bb.png)

Can confirm, on Linux its even worse.. BrowserWindow doesn't seem to fill the whole desktop window, and then the BrowserWindow keeps the same (incorrect) aspect ratio with which it was launched whenever your resize the desktop window.

Using arch / i3-gaps here.

**Comment by alexkim205** [comment]
> Also darkmode seems to mess up the profile picture on the Gmail Hangouts chat widget in the left sidebar. Compare my profile picture in the above screenshot to this:
> 
> ![image](https://user-images.githubusercontent.com/7415984/82128312-77edb600-97ba-11ea-822a-081257372d5c.png)

A simple fix for this could be to invert everything but the images. Something like this inverting the images back could work: 
```
html {
    filter: invert(100%);
}
img {
    filter: invert(100%);
}

```

**Comment by alexkim205** [comment]
After some hair pulling, it looks like using `BrowserWindow.getContentBounds()` instead of `getBounds()` gets the true dimensions of the screen that lie within the window. 

This should fix the awkward window sizing issue that was happening in linux and windows but not macos. These changes also don't seem to be breaking the sizing on macs.
