### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by wmorrel** [alexkim205/G-Desktop-Suite#23]
Any plans to [create](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) a [Homebrew tap](https://docs.brew.sh/Taps) for this project? It looks awesome and I'd love an easy way to keep up-to-date!

**Comment by alexkim205** [comment]
That'd be pretty cool. I personally don't have any experience with this but I'll look into it!

**Comment by wmorrel** [comment]
Nice! I've never rolled a homebrew tap myself either, but can vouch for how awesome Homebrew is for installing and managing packages on macOS.

**Comment by nathang21** [comment]
+1 this would love this for automatic updates and easy installation on multiple devices. Congrats on the visibility today!

**Comment by mding5692** [comment]
Some links that might help: 
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://stackoverflow.com/questions/28241061/set-up-a-homebrew-tap-with-a-git-repository-on-a-private-network
https://jonathanchang.org/blog/maintain-your-own-homebrew-repository-with-binary-bottles/
https://medium.com/prodopsio/creating-homebrew-taps-for-private-internal-tools-c41363d58ab0

Downloaded and using this right now, looks great!

**Comment by nitrocode** [comment]
It might not be too difficult. There are a few yarn apps in homebrew already.

See this query for [`depends_on yarn`](https://github.com/Homebrew/homebrew-core/search?q=depends_on+yarn&unscoped_q=depends_on+yarn) in the [homebrew-core](https://github.com/Homebrew/homebrew-core) project.

Homebrew does have a policy against [self-submitting](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff)

> We frown on authors submitting their own work unless it is very popular.

but judging by the stars alone, this app does seem popular.

**Comment by alexkim205** [comment]
Thanks for the suggestion. Currently I'm looking into using `brew cask` which looks like it would be more appropriate for installing and maintaining macos apps with guis. Please check out this linked PR #36 for the latest progress on this ticket.

**Comment by alexkim205** [comment]
Thanks everyone for your suggestions. G Desktop Suite has been accepted into the homebrew-cask family and can now be installed with `brew cask install g-desktop-suite`. Please see the README for more details on how to install.

**Comment by wmorrel** [comment]
Nice work! Thanks!
