### ISSUE TITLE
Doesn't work with 2 Factor Authentication 

### ISSUE THREAD

**Issue by acgh213** [alexkim205/G-Desktop-Suite#24]
Tried to login, and the redirect just opening up the google login page again. Possible fix would be allowing the redirect to the main window, and continue with the 2 auth. 

Using an app password did not work, prompting me for my account password and not with my app password I had created.

**Comment by simonpacis** [comment]
No problem with 2-factor auth here. Works as expected.

**Comment by alexkim205** [comment]
@acgh213 Could you let me know what platform you're on?

**Comment by ndom91** [comment]
2fa worked here in win10 as well.

**Comment by willsheldon** [comment]
Confirmed, does not work with u2f security token on mac. "Browser does not support security keys" https://i.imgur.com/mKF5YUh.png

**Comment by ndom91** [comment]
Found some info on webauthn and electron here: https://github.com/electron/electron/issues/15404

Seems you have to disable `nodeIntegration` when loading the remote site, but otherwise U2F and webauthn are natively supported by chrome for a while now, should work no problem.

**Comment by alexkim205** [comment]
@willsheldon & @acgh213. This recent security patch [commit](https://github.com/alexkim205/G-Desktop-Suite/commit/bd9fb5f16c49b34f05eec919edfbb001ad46bccd) should address the node integration issue that @ndom91 brought up. I've tested 2FA on my mac and windows machines and both seem to be working fine. 

Could you try building the most recent version of the repository and let me know if you run into the same problems? The code below should get you started.

```
git clone https://github.com/alexkim205/G-Desktop-Suite.git
cd G-Desktop-Suite
yarn install
yarn start
```

**Comment by ndom91** [comment]
2FA with the "Tap Yes On Your Phone" method continues to work with the latest `master`. Unfortunately I don't have any hardware keys to test the other methods with.

**Comment by acgh213** [comment]
@alexkim205 The fix worked for me, thank you very much. 2FA usb security key is working along side "Tap yes on your phone"
