### ISSUE TITLE
Unsupported browser warning

### ISSUE THREAD

**Issue by mding5692** [alexkim205/G-Desktop-Suite#25]
### Version Details
OS: MacOS v10.13.6 High Sierra
Release version: Conscious Club

### Issue Description:
Using MacOS and most recent version, seeing this warning after I login and check out my google drive

Screenshot:
![Screen Shot 2020-05-16 at 12 54 34 AM](https://user-images.githubusercontent.com/9067177/82110997-d90c7f80-970f-11ea-9173-cb28dd138d45.png)

Text:
`You are using an unsupported browser. If you see some unexpected behavior, you may want to use a supported browser instead. LEARN MORE`

Might be related to this: https://github.com/cryptonomex/graphene-ui/issues/572

**Comment by mding5692** [comment]
Learn More button is clickable, brought me here:

![Screen Shot 2020-05-16 at 12 59 50 AM](https://user-images.githubusercontent.com/9067177/82111113-9f884400-9710-11ea-86ed-3a0969b89032.png)

**Comment by mding5692** [comment]
I can help out on it @alexkim205 know which files this might be linked to?

**Comment by mding5692** [comment]
Was checking browser version on development environment using this command:
https://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browser

![Screen Shot 2020-05-16 at 12 59 50 AM](https://user-images.githubusercontent.com/9067177/82129297-925e6a00-978f-11ea-8c03-e316c0155fa6.png)

**Comment by mding5692** [comment]
This might be a workaround solution for now: https://stackoverflow.com/questions/51017928/electron-webview-chrome-is-obsolete

**Comment by mding5692** [comment]
Ok @alexkim205 

Set useragent in config.js like so:
`const userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36";`

and it worked

**Comment by alexkim205** [comment]
Thanks for taking the time to look into this. This temporary fix works great on my Mac and I can test it on a Windows machine I have lying around.

I would greatly appreciate if someone with a Linux machine could check out @mding5692 's #31 PR. I'm considering firing up a Linux VM as well.

**Comment by mding5692** [comment]
Yea no worries, don't think this is an Electron version issue, I tried it with latest Electron version and did not fix. This is probably related to the user agent and how its parsed by Google Drive.

**Comment by alexkim205** [comment]
Also tested this with Windows, and I get the same unsupported browser warning too.

**Comment by mding5692** [comment]
@alexkim205 Think its basically happening for all OSes, this is dependant on useragent string constant and basically Google Drive probably just reads that

**Comment by YodaLightsabr** [comment]
Would it be possible to interact with the page and force the popup to be hidden? We know it functions just fine and it's just a problem with the user agent, so it doesn't seem like it would be a big problem to do that.
