### ISSUE TITLE
About window -  cannot read `copyright` of undefined

### ISSUE THREAD

**Issue by ndom91** [alexkim205/G-Desktop-Suite#28]
On windows 10:

![image](https://user-images.githubusercontent.com/7415984/82128365-eb8fc300-97ba-11ea-964f-9605b567390f.png)

I'm assuming its talking about this https://github.com/alexkim205/G-Desktop-Suite/blob/bfe94093a02e62bd55479491e28e18533901ab2b/src/javascripts/menu.js#L10

But if `appInfo.productName` right above it resolves, then I dont get how `appInfo.build.copyright`. `build` is most definitely there in the toplevel of the package.json

**Comment by alexkim205** [comment]
Adding `package.json` into the `build` files seems to solve the issue. 

![Annotation 2020-05-17 050023](https://user-images.githubusercontent.com/13460330/82140105-5a8d0c00-97fb-11ea-9282-bf491271f8bd.png)
