### ISSUE TITLE
“gdesktopsuite” terminated by signal SIGTRAP (Trace or breakpoint trap)

### ISSUE THREAD

**Issue by leonqli** [alexkim205/G-Desktop-Suite#32]
```bash
$sudo dpkg -i gdesktopsuite_0.2.0_amd64.deb
$gdesktopsuite
fish: “gdesktopsuite” terminated by signal SIGTRAP (Trace or breakpoint trap)
```
My system info:
```bash 
Linux 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux
```

**Comment by alexkim205** [comment]
Could you try downloading the more recent releases? I've changed the way I packaged the executables and this might be a bug related to an older version. However if you're still running into the same issues, you're more than welcome to reopen the issue!
