### ISSUE TITLE
Text focus on cmd+tab window switching

### ISSUE THREAD

**Issue by masonlr** [alexkim205/G-Desktop-Suite#37]
**Describe the bug**

When switching to an app window using cmd+tab or cmd+` the text entry does not have focus. This means that you have to click somewhere before you can type.

**To Reproduce**
1. Open another app
2. Change windows to G Desktop Suite using cmd+tab
3. Try typing

**Expected behavior**
Be able to cmd+tab to a google docs window and start typing without using a mouse.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.4

**Comment by alexkim205** [comment]
@masonlr This a nice catch! This problem should be fixed in the latest release.
