### ISSUE TITLE
[💡 FEATURE] - Allow Manual Toggle Light/Dark Mode

### ISSUE THREAD

**Issue by alexduncan** [alexkim205/G-Desktop-Suite#39]
**Describe the problem**
My system is set to dark mode, but I prefer to use Google Drive in light mode.

**Expected behavior**
Add a preference or menu option to allow me set it to light mode.

**G Desktop Suite:**
 - Version Not sure

**Platform:**
 - OS: MacOSX
 - Version: 10.15.4

**Additional context**
Many other apps like Apple Mail and Sketch allow independent tweaking separate from the system setting. e.g. Mail allows your emails to still appear in white and Sketch allows you to set your canvas to be light

**Comment by alexkim205** [comment]
This is something that's definitely on the roadmap. I'm thinking I'll roll this out with a separate preferences window and/or a keyboard shortcut you can toggle the theme with.

**Comment by muttleyxd** [comment]
+1 on this, also autodetection doesn't work in my case on Arch Linux with XFCE (I use Arc Dark theme). I think it's not viable to support 2^10 Linux DE's manually, so dark mode toggle would be very welcome.

**Comment by eiras5g** [comment]
This is available? I'm using the 0.2.1 version in my Windows 10 and I can't find the menu to change my theme. Dark mode is crashing the app, I want to change for the light theme.

**Comment by alexkim205** [comment]
Hi @eiras5g thanks for trying out the app. As of yet manual toggling of themes is not available, however I am currently working on a solution for the next release. 

If anyone with some time on their hands would like to take a crack at it with a PR, I would greatly appreciate it! To get you started in the right direction, I define all the global shortcuts in [menu.js](https://github.com/alexkim205/G-Desktop-Suite/blob/master/src/javascripts/menu.js) and do the actually toggling in preload scripts that are injected into the browser window (the main Electron window [preload.js](https://github.com/alexkim205/G-Desktop-Suite/blob/master/src/javascripts/preload.js)) and view (the web frame displaying the contents of Google Drive [preload-view.js](https://github.com/alexkim205/G-Desktop-Suite/blob/master/src/javascripts/preload-view.js))

**Comment by eiras5g** [comment]
Thanks for the answer Alex! However, can I change any configuration for disable the Dark Theme? Or resolve the invert color problem?

**Comment by mding5692** [comment]
@alexkim205 I can open a PR like you said using keyboard shortcuts to toggle light/dark mode

**Comment by mding5692** [comment]
> To get you started in the right direction, I define all the global shortcuts in [menu.js](https://github.com/alexkim205/G-Desktop-Suite/blob/master/src/javascripts/menu.js) and do the actual theme toggling in preload scripts that are injected into the browser window (the main Electron window [preload.js](https://github.com/alexkim205/G-Desktop-Suite/blob/master/src/javascripts/preload.js)) and view (the web frame displaying the contents of Google Drive [preload-view.js](https://github.com/alexkim205/G-Desktop-Suite/blob/master/src/javascripts/preload-view.js))

Hey @alexkim205 noticed you used the same kind of method in these files, can probably take that method out and re-use it

**Comment by alexkim205** [comment]
Thanks! Feel free to assign me as a reviewer.

**Comment by alexkim205** [comment]
> Hey @alexkim205 noticed you used the same kind of method in the preload js files, can probably take that method out and re-use it

That's probably a better way to refactor it. Maybe creating a method in the `utils.js`? It's totally at your discretion.

**Comment by mprogano** [comment]
+1 on this

**Comment by andremacola** [comment]
Google Docs with dark mode is nonsense. We need to visualize the documents with original colors.
