### ISSUE TITLE
[🐛 BUG] - G suite application can't open another apps

### ISSUE THREAD

**Issue by RMurari** [alexkim205/G-Desktop-Suite#40]
Very cool product. I can launch all Google apps from the Desktop Suite. However, if have opened Sheets from Desktop Suite and if i try to open Docs within the Sheets Google Apps its not working. I will have to use the Desktop Suite to open other apps. Is this expected behavior ?
thanks

**Comment by alexkim205** [comment]
I think it makes more sense that you don't have to be in the Suite window to create new file windows. In order for me to reproduce this behavior, could you provide more details on how you're opening another doc from within google sheets? Is it through just a shared link in a cell?

**Comment by RMurari** [comment]
here are the steps..
Open the App Desktop Suite. 
Once this is Opened,I Go to Google Apps ( the nine dots on the top left).
![image](https://user-images.githubusercontent.com/65527163/82296738-4437a980-99cf-11ea-9a24-2d71b5907dcd.png)
Click the Sheets logo and Sheets opened now.
Now I am in Sheets and again I go to Google Apps and select Docs, the click does not work.
However you can open all the Google Apps from the 9 nine dots in the App Desktop Suite.
hope this is clear..

**Comment by alexkim205** [comment]
Version 0.3.1 is out. Using the latest version will fix your issue. Thanks for being patient!

**Comment by RMurari** [comment]
thanks. the issue seems resolved now and can open all the G Suite applications after an application is opened as well.
