### ISSUE TITLE
[🐛 BUG] - Darkmode is inverting the content

### ISSUE THREAD

**Issue by madshensel** [alexkim205/G-Desktop-Suite#42]
**Describe the bug**
Dark mode inverted the images on my slides?!

**To Reproduce**
Open a slide with background images and they will be inverted.

**Expected behavior**
Dark mode not involving the content of slides.

**Screenshots**

**G Desktop Suite:**
 - Version 0.2.1

**Platform:**
 - OS: MacOSX, Windows, Linux
 - Version 10.15.3

**Comment by alexkim205** [comment]
> Also darkmode seems to mess up the profile picture on the Gmail Hangouts chat widget in the left sidebar. Compare my profile picture in the above screenshot to this:
> 
> ![image](https://user-images.githubusercontent.com/7415984/82128312-77edb600-97ba-11ea-822a-081257372d5c.png)

A simple fix for this could be to invert everything but the images. Something like this inverting the images back could work: 
```
html {
    filter: invert(100%);
}
img {
    filter: invert(100%);
}

```

This looks like an issue separate from window sizing, so I'll move discussion about inverted image colors to #42.

_Originally posted by @alexkim205 in https://github.com/alexkim205/G-Desktop-Suite/issues/22#issuecomment-630294944_
