### ISSUE TITLE
[🐛 BUG] - Window title is not updated when changing application

### ISSUE THREAD

**Issue by muttleyxd** [alexkim205/G-Desktop-Suite#44]
**Describe the bug**

**To Reproduce**
1. Login, default app opens, in my case `Google Drive`
2. Switch app to another one, eg. Hangouts
3. Hangouts are launched with `Google Drive` window title

**Expected behavior**
3. Hangouts are launched with `Google Hangouts` title

**Screenshots**
![work](https://user-images.githubusercontent.com/9843181/82327861-54578500-99df-11ea-9d46-041df9515e21.png)

**G Desktop Suite:**
 - Version - g-desktop-suite-git 122.315a78a-1

**Platform:**
 - OS: Arch Linux, XFCE desktop environment

**Comment by mding5692** [comment]
Right now window title is managed by a static index.html file, maybe something can update that?

**Comment by alexkim205** [comment]
This has been fixed with merging PR #48.
