### ISSUE TITLE
[💡 FEATURE] - encyption feature while upload to gsuit

### ISSUE THREAD

**Issue by DEVUVO** [alexkim205/G-Desktop-Suite#46]
Hello , is it possible to add encryption feature to the app with some strong key to use it also for decrypt the files when key is provided , like rclone ? 

rclone is cool but not an easy for me many people like how its but its not an easy gui for windows users who dont want to deal with configuration and long story setup
i tried many apps , and rclone browser and many rclone passed gui , web gui etc , all are hard to config .
this will make a big different , thanks in advance.

**Comment by alexkim205** [comment]
Unfortunately for security reasons, this app won't deal with encrypting the actually files on Google Drive themselves because they will never exist on the local drive.
