### ISSUE TITLE
[💡 FEATURE] - Open links in default browser instead of new Electron window

### ISSUE THREAD

**Issue by ChocoTonic** [alexkim205/G-Desktop-Suite#5]
can you make it so that links clicked on in the document go to the default browser instead of another window?

**Comment by ithieund** [comment]
@alexkim205 , can you make this happen in next release?
This is a must have feature :)

**Comment by motiveunknown** [comment]
I'm not able to open links from Gmail at all

**Comment by mding5692** [comment]
@alexkim205 Probably want to implement [this](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl) in a helper function somewhere

**Comment by alexkim205** [comment]
Version 0.3.1 is out. Using the latest version will fix your issue. Thanks for being patient!
