### ISSUE TITLE
[💡 FEATURE] - Window hiding on macOS (cmd+H)

### ISSUE THREAD

**Issue by masonlr** [alexkim205/G-Desktop-Suite#56]
**Describe the feature**

On macOS, window hiding (default cmd+H shortcut) doesn't work.

**To Reproduce**
1. Go to a doc
2. Type cmd+H shortcut
3. Nothing happens

**Expected behavior**
Window should be hidden when cmd+H is pushed.

**Platform:**
 - OS: macOS

**Comment by alexkim205** [comment]
Thanks for bringing this functionality to my attention. I'm relabelling this as a feature as it hasn't been implemented yet.

**Comment by alexkim205** [comment]
Version 0.3.1 is out. Using the latest version will fix your issue. Thanks for being patient!

**Comment by masonlr** [comment]
Thanks. Trying to help with user feedback to improve the app. Keep up the good work.
