### ISSUE TITLE
[💡 FEATURE] - Add auto-updating.

### ISSUE THREAD

**Issue by alexkim205** [alexkim205/G-Desktop-Suite#63]
**Is your feature request related to a problem? Please describe.**
Deploying key updates to users is difficult when there is no auto updating baked into the app. 

**Describe the solution you'd like**
Look into using electron builder's auto update functionality.
[https://www.electron.build/auto-update](https://www.electron.build/auto-update)

**Additional context**
For Mac users, it looks like auto update won't work without an Apple signing certificate. I don't have the money to drop on that :( but hopefully publishing updates on cask can be an easy alternative for Mac users.

**Comment by mding5692** [comment]
I can help out with this, apologies, been busy these days

**Comment by alexkim205** [comment]
No worries! I've been working on this on a separate branch but I'll create a PR for it soon.

**Comment by mding5692** [comment]
Ok cool
