### ISSUE TITLE
Login to google not allowed in app via security issue

### ISSUE THREAD

**Issue by michalradacz** [alexkim205/G-Desktop-Suite#73]
**Describe the bug**
When I try to login to app, after enterring email, google says, that this browser or application cannot be used via security issue with this app. I am using my personal Google account without any super security settings or great security account level.

**To Reproduce**
1. Install the app.
2. Run the app for first time
3. Wait to inform that this is current version.
4. Standard google login fform appears.
5. Enter e-mail of my account and press Next (Další in czech)
6. Security alert appears from Google for this app.

**Expected behavior**
Login

**Screenshots**

**G Desktop Suite:**
 - Version 0.3 - latest release

**Platform:**
 - OS: Windows 10
 - Version [e.g. 10]

**Comment by alexkim205** [comment]
Thanks for leaving this ticket. We noticed this problem as soon as the release came out, and we pushed a hotfix to the `master` branch. Version 0.3.1 with the fixes will be coming out by the end of today, so please hang tight!

**Comment by alexkim205** [comment]
Version 0.3.1 is out. Using the latest version will fix your issue. Thanks for being patient!
