### ISSUE TITLE
[🐛 BUG] - Styling making the app unusable. 

### ISSUE THREAD

**Issue by samiq** [alexkim205/G-Desktop-Suite#77]
**Describe the bug**
Launching the app makes the styling not resize after the animation to maximise the screen, making the app look weird, problem is with every new launch the styling keeps shrinking.

**To Reproduce**
1. Launch the app
2. Wait for the app to animate the screen maximization

**Expected behavior**
The app should render the Drive dashboard on a maximised screen, no blank spaces.

**Screenshots**
<img width="1552" alt="Screenshot 2020-05-26 at 09 21 57" src="https://user-images.githubusercontent.com/220773/82877641-5d41dc80-9f32-11ea-84e6-2493f2ed3a0a.png">

**G Desktop Suite:**
 - Version 0.2.1

**Platform:**
 - OS: Mac OS
 - Version 10.15.4

**Additional context**
this was working just fine on Friday

**Comment by alexkim205** [comment]
Hey @samiq thanks for filing this issue. It looks like you’re using a relatively older version of this app. Could you try installing V0.3.1 and let me know if you run into the same problem?

**Comment by samiq** [comment]
got it, thanks for the response, just updated this by installing it by brew, thought the app will prompt when there is an update. cheers!
