### ISSUE TITLE
[🧹 CODE QUALITY] - Update dark mode

### ISSUE THREAD

**Issue by Gusted** [alexkim205/G-Desktop-Suite#86]
**What do you want to clean or refactor?**
The package.json darkreader version

**Why?**
We added between 4.9.2 and 4.9.15 a lot of fixes to G-Suite websites to make them even better :D(I'm from the Dark Reader team)
It shouldn't be hard to bump that number and also get some other fixes along side it like performance that was introduced in 4.9.9 to make it the dark mode faster :D

**Comment by Gusted** [comment]
Here some CSS fixes that we has been added since 4.9.2

https://github.com/darkreader/darkreader/compare/f9afdc08136388b2fa45dc0ebc994168899d3acb...master#diff-586490987f1183cd5d148a7688a09127L552

https://github.com/darkreader/darkreader/compare/f9afdc08136388b2fa45dc0ebc994168899d3acb...master#diff-586490987f1183cd5d148a7688a09127L1450

https://github.com/darkreader/darkreader/compare/f9afdc08136388b2fa45dc0ebc994168899d3acb...master#diff-586490987f1183cd5d148a7688a09127R1119

https://github.com/darkreader/darkreader/compare/f9afdc08136388b2fa45dc0ebc994168899d3acb...master#diff-586490987f1183cd5d148a7688a09127R620

https://github.com/darkreader/darkreader/compare/f9afdc08136388b2fa45dc0ebc994168899d3acb...master#diff-586490987f1183cd5d148a7688a09127R657

https://github.com/darkreader/darkreader/compare/f9afdc08136388b2fa45dc0ebc994168899d3acb...master#diff-586490987f1183cd5d148a7688a09127R1165

https://github.com/darkreader/darkreader/compare/f9afdc08136388b2fa45dc0ebc994168899d3acb...master#diff-586490987f1183cd5d148a7688a09127R1908

**Comment by andremacola** [comment]
Google Docs with dark mode is nonsense. We need to visualize the documents with original colors, especially business documents. Need a toggle to manual disable the dark mode.
